version: 1
services:
  web:
    type: node
    name: vscode-web-app
    env: 
      NODE_ENV: production
    buildCommand: npm install && npm run build
startCommand: node server.js
    plan: free
    region: oregon
